// Copy this file to config.dart and fill in your actual values.
// config.dart is gitignored and must never be committed.

const String directusBaseUrl = 'https://your-directus-instance.example.com';
const String directusAccessToken = 'your-access-token-here';

// UUID of the Directus role that grants editor permissions (can edit events/courses).
// Find this in the Directus admin UI under Settings → Roles.
const String editorRoleId = 'your-editor-role-uuid-here';

// Base URL of the Dancee workflow service (Restate HTTP proxy).
// Used for fire-and-forget retranslation triggers after edits.
const String workflowBaseUrl = 'https://your-workflow-service.example.com';

// Firebase configuration is NOT stored here.
// It is generated by the FlutterFire CLI into lib/firebase_options.dart.
// Run: `flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID`
// See docs/FIREBASE_AUTH_SETUP.md for full setup instructions.
