// Copy this file to config.dart and fill in your actual values.
// config.dart is gitignored and must never be committed.

const String directusBaseUrl = 'https://your-directus-instance.example.com';
const String directusAccessToken = 'your-access-token-here';

// Firebase configuration is NOT stored here.
// It is generated by the FlutterFire CLI into lib/firebase_options.dart.
// Run: `flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID`
// See docs/FIREBASE_AUTH_SETUP.md for full setup instructions.
