// Generated by FlutterFire CLI — run `flutterfire configure` to regenerate.
// This file contains Firebase project configuration (project IDs, not secrets).
// It is safe to commit to version control.
//
// To generate this file for your Firebase project:
//   1. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
//   2. Run: `flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID`
//
// The placeholder values below must be replaced with real Firebase configuration
// before the app can authenticate. See docs/FIREBASE_AUTH_SETUP.md for details.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVScsqpCulertRQ_actn4dWaT0blKruZ8',
    appId: '1:776014571343:web:665ab22687e6c4bd23873a',
    messagingSenderId: '776014571343',
    projectId: 'dancee-b5c0d',
    authDomain: 'dancee-b5c0d.firebaseapp.com',
    storageBucket: 'dancee-b5c0d.firebasestorage.app',
    measurementId: 'G-XL57C7BNHW',
  );

  // TODO: Replace with values from `flutterfire configure`

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUrSxRgoRwOvjzD4xRGN1mZBugmEIjbY',
    appId: '1:776014571343:android:af3b8ee98d7ab53523873a',
    messagingSenderId: '776014571343',
    projectId: 'dancee-b5c0d',
    storageBucket: 'dancee-b5c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTgYbZwQ31eipF19jf_9IPMqPnLINFBY',
    appId: '1:776014571343:ios:76322ac84a07816223873a',
    messagingSenderId: '776014571343',
    projectId: 'dancee-b5c0d',
    storageBucket: 'dancee-b5c0d.firebasestorage.app',
    iosClientId: '776014571343-iin8t2a84h1bc1uka20ijbvngrten4kv.apps.googleusercontent.com',
    iosBundleId: 'com.jablecnik.dancee-app',
  );

}